@endpoint=http://localhost:8080

### 查询所有jar依赖
GET {{endpoint}}/api/jar/dependencies
Content-Type: application/json


### 查询APP依赖
GET {{endpoint}}/api/jar/dependencies/UjQhM2mOOR7I
Content-Type: application/json


### 匹配依赖项, 与app依赖项进行匹配
POST {{endpoint}}/api/jar/dependencies/match
Content-Type: application/json

{
    "appId": "UjQhM2mOOR7I",
    "dependencies": ["guava-18.0.jar", "trest.jar"]
}

### 不匹配依赖项, 与app依赖项进行匹配
POST {{endpoint}}/api/jar/dependencies/mismatch
Content-Type: application/json

{
    "appId": "UjQhM2mOOR7I",
    "dependencies": ["guava-18.0.jar", "trest.jar"]
}


### 注入 (TBD)
POST {{endpoint}}/api/jar/dependencies/inject
Content-Type: application/json

