### checksum
@endpoint=http://localhost:8080

### 检查lib的不匹配项
### majar=true 跳过版本号的比较
GET {{endpoint}}/api/jar/dep/mismatch
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar
//&major=true
&major=false
Content-Type: application/json


### 返回两个JAR的匹配项
GET {{endpoint}}/api/jar/dep/match
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar
&major=true
Content-Type: application/json


### 查询jar依赖+checksum
// type: default: md5l
//   supported: adler32,crc32,crc32c,md5,sha1,sha256,sha512
//   endsWith "l", means padToLong
GET {{endpoint}}/api/jar/dep/checksum
?jar=jar-dependency-api-1.0.0-standalone.jar
&pattern=jar-dependency
### 查询指定目录lib下的jar依赖
GET {{endpoint}}/api/jar/dep/checksum
?jar=jar-dependency-api-1.0.0.jar
&dir=lib
&type=md5l


### 依据checksum检查两个jar的更新依赖
GET {{endpoint}}/api/jar/dep/checksum/mismatch
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar
Content-Type: application/json

