###################  am配置  ###################
am:
  swagger-open: true #是否开启swagger (true/false)

###################  jwt配置  ###################
jwt:
  encoded-key: L7A/6zARSkK1j7Vd5SDD9pSSqZlqF7mAhiOgRbgv9Smce6tf4cJnvKOjtKPxNNnWQj+2lQEScm3XIUjhW+YVZg==
  normal-encoded-key: bm9ybWFsLWVuY29kZWQta2V5
  #tll-mills:
  #token-type: Bearer

###################  项目启动配置  ###################
server:
  port: 8080
###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view/
      suffix: .html
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson

jar-dependency:
   root-path: jar-dependency-api/target
   container: testapi
   docker-api-endpoint: http://192.168.3.239:2375
   